### PR TITLE
PicoMicroNanoMacro optimize memory

### PR DESCRIPTION
**Pull request by GermanAizek**
Usage less memory ~8 bytes and less cycles in init `find()`

Signed-Off: Herman Semenov <GermanAizek@yandex.ru>

### CODE REVIEW

**Comment by GermanAizek** [comment]
image

**Comment by SrMilton** [comment]
I need to release a V2 update with this awesome idea, will be a life changer hahahahah

**Comment by GermanAizek** [comment]
@SrMilton,
Can you help with json integration?
I used [picojson](https://github.com/kazuho/picojson) here:
https://github.com/GermanAizek/webdriverxx
This is very lightweight header-only 3rd party.

**Review by SrMilton — APPROVED** [review]
Life changer

**Comment by SrMilton** [comment]
> @SrMilton,
> Can you help with json integration?
> I used [picojson](https://github.com/kazuho/picojson) here:
> https://github.com/GermanAizek/webdriverxx
> This is very lightweight header-only 3rd party.

I was using json, but please read the end of README... :(

**Pull request merged**
